title: griccardos
description: projects
taglong: Software engineer
tagshort: Projects

url: https://griccardos.github.io
baseurl: ""
permalink: pretty
repo: https://github.com/griccardos/griccardos.github.io

# build settings

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-gist

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  sourcemap: never

autopages:
  enabled: false
